// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABOQz5h4zZgMHLGuJTRIiX6hITE3fg2TM',
    appId: '1:61725826475:web:4ed8a8ec6a58d35322c6ee',
    messagingSenderId: '61725826475',
    projectId: 'aidkriya-294dc',
    authDomain: 'aidkriya-294dc.firebaseapp.com',
    storageBucket: 'aidkriya-294dc.firebasestorage.app',
    measurementId: 'G-8LSFEBD3KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOhNZZOuI1ukgiqfdQ5tT_Xy4Lm4XEqLM',
    appId: '1:61725826475:android:828bb76c6a1d6fa722c6ee',
    messagingSenderId: '61725826475',
    projectId: 'aidkriya-294dc',
    storageBucket: 'aidkriya-294dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMyd-ZEjejPe1ZF38YaE348belIatdY3E',
    appId: '1:61725826475:ios:3b3746cbf86746c122c6ee',
    messagingSenderId: '61725826475',
    projectId: 'aidkriya-294dc',
    storageBucket: 'aidkriya-294dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMyd-ZEjejPe1ZF38YaE348belIatdY3E',
    appId: '1:61725826475:ios:3b3746cbf86746c122c6ee',
    messagingSenderId: '61725826475',
    projectId: 'aidkriya-294dc',
    storageBucket: 'aidkriya-294dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABOQz5h4zZgMHLGuJTRIiX6hITE3fg2TM',
    appId: '1:61725826475:web:ae2c89650ac873cd22c6ee',
    messagingSenderId: '61725826475',
    projectId: 'aidkriya-294dc',
    authDomain: 'aidkriya-294dc.firebaseapp.com',
    storageBucket: 'aidkriya-294dc.firebasestorage.app',
    measurementId: 'G-2SPJZZJFN6',
  );
}
